name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com/"
          scope: "shiva1418"
      - run: npm install
      - run: npm ci
   #   - run: npm publish
      - run: npm publish | find . -type f -iname "package.json" | sed -r 's|/[^/]+$||' |sort |uniq
#             Get-ChildItem -r -Include package.json | % {
#               Write-Host $_.Directory
#               Write-Host $_.FullName
#               npm publish $_.Directory
#            }
#              find ./node-modules -f "package.json"
#                 Write-Host $_.Directory
#                 Write-Host $_.FullName
#                 npm publish $_.Directory
 
   #   - run: npm version minor
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
