name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com/"
          scope: "shiva1418"
      - run: npm install
      - run: npm ci
      - run: npm publish
   #   - run: npm version minor
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#       - name: Download Artifact
#         uses: actions/download-artifact@v2
#         with:
#          name: '${{ env.PROJECT-NAME }}.${{ env.VERSION-MAJOR }}.${{ env.VERSION-MINOR }}.${{ env.VERSION-PATCH }}.${{ github.run_number }}'    
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v2
#         with:
#          name: '${{ env.PROJECT-NAME }}.${{ env.VERSION-MAJOR }}.${{ env.VERSION-MINOR }}.${{ env.VERSION-PATCH }}.${{ github.run_number }}'
#          path: build/distributions/*.tgz
#          if-no-files-found: error
